import 'package:flutter/material.dart';

final ThemeData thatExoticBugTheme = ThemeData(
  brightness: Brightness.dark,
  buttonTheme: const ButtonThemeData(
    alignedDropdown: false,
    colorScheme: ColorScheme(
      brightness: Brightness.dark,
      background: Color(0xff2b3338),
      error: Color(0xffcf6679),
      errorContainer: Color(0xffcf6679),
      inversePrimary: Color(0xff000000),
      inverseSurface: Color(0xffffffff),
      onBackground: Color(0xffffffff),
      onError: Color(0xff000000),
      onErrorContainer: Color(0xff000000),
      onInverseSurface: Color(0xff334213),
      onPrimary: Color(0xff000000),
      onPrimaryContainer: Color(0xff000000),
      onSecondary: Color(0xff000000),
      onSecondaryContainer: Color(0xff000000),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      onTertiary: Color(0xff000000),
      onTertiaryContainer: Color(0xff000000),
      outline: Color(0xffffffff),
      outlineVariant: Color(0xffffffff),
      primary: Color(0xffd6c944),
      primaryContainer: Color(0xffb9ad39),
      secondary: Color(0xff49dcc1),
      secondaryContainer: Color(0xff3dbea6),
      shadow: Color(0xff000000),
      surface: Color(0xff334213),
      surfaceTint: Color(0xffd6c944),
      surfaceVariant: Color(0xff334213),
      tertiary: Color(0xff49dcc1),
      tertiaryContainer: Color(0xff49dcc1),
    ),
    height: 36,
    layoutBehavior: ButtonBarLayoutBehavior.padded,
    minWidth: 88,
    padding: EdgeInsets.only(bottom: 0, left: 16, right: 16, top: 0),
    textTheme: ButtonTextTheme.normal,
  ),
  canvasColor: const Color.fromARGB(255, 5, 43, 66),
  cardColor: const Color(0xff334213),
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    background: Color(0xff2b3338),
    error: Color(0xffcf6679),
    errorContainer: Color(0xffcf6679),
    inversePrimary: Color(0xff000000),
    inverseSurface: Color(0xffffffff),
    onBackground: Color(0xffffffff),
    onError: Color(0xff000000),
    onErrorContainer: Color(0xff000000),
    onInverseSurface: Color(0xff334213),
    onPrimary: Color(0xff000000),
    onPrimaryContainer: Color(0xff000000),
    onSecondary: Color(0xff000000),
    onSecondaryContainer: Color(0xff000000),
    onSurface: Color(0xffffffff),
    onSurfaceVariant: Color(0xffffffff),
    onTertiary: Color(0xff000000),
    onTertiaryContainer: Color(0xff000000),
    outline: Color(0xffffffff),
    outlineVariant: Color(0xffffffff),
    primary: Color(0xffd6c944),
    primaryContainer: Color(0xffb9ad39),
    secondary: Color(0xff49dcc1),
    secondaryContainer: Color(0xff3dbea6),
    shadow: Color(0xff000000),
    surface: Color(0xff334213),
    surfaceTint: Color(0xffd6c944),
    surfaceVariant: Color(0xff334213),
    tertiary: Color(0xff49dcc1),
    tertiaryContainer: Color(0xff49dcc1),
  ),
  dialogBackgroundColor: const Color(0xff2b3338),
  disabledColor: const Color(0x62ffffff),
  dividerColor: const Color(0x1fffffff),
  focusColor: const Color(0x1fffffff),
  highlightColor: const Color(0x40cccccc),
  hintColor: const Color(0x99ffffff),
  hoverColor: const Color(0x0affffff),
  iconTheme: const IconThemeData(color: Color(0xffffffff)),
  indicatorColor: const Color(0xffffffff),
  inputDecorationTheme: const InputDecorationTheme(
    alignLabelWithHint: false,
    filled: false,
    floatingLabelAlignment: FloatingLabelAlignment.start,
    floatingLabelBehavior: FloatingLabelBehavior.auto,
    isCollapsed: false,
    isDense: false,
  ),
  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
  platform: TargetPlatform.android,
  primaryColor: const Color(0xff334213),
  primaryColorDark: const Color(0xff000000),
  primaryColorLight: const Color(0xff9e9e9e),
  primaryIconTheme: const IconThemeData(color: Color(0xffffffff)),
  scaffoldBackgroundColor: const Color(0xff2b3338),
  secondaryHeaderColor: const Color(0xff616161),
  shadowColor: const Color(0xff000000),
  splashColor: const Color(0x40cccccc),

);
